---
# Tasks
# TODO make this dependent on the apache role instead of installing the package
- name: Ensure apache2 mellon module is installed
  package:
    name: libapache2-mod-auth-mellon
    state: present


- name: Ensure mellon config directory exists
  file:
    path: "{{ mellon_sp_cfg_dir }}"
    state: directory
    mode: 0755


- name: Ensure SAML key is available
  copy:
    content: "{{ mellon_sp_key }}"
    dest: "{{ mellon_sp_cfg_dir }}/sp.key"
    mode: 0640
    group: "ssl-cert"


- name: Ensure SAML cert is available
  copy:
    content: "{{ mellon_sp_crt }}"
    dest: "{{ mellon_sp_cfg_dir }}/sp.crt"


- name: Change IdP metadata string to list
  set_fact:
    mellon_sp_remote_idp_metadata_url:
      - "{{ mellon_sp_remote_idp_metadata_url }}"
  when: mellon_sp_remote_idp_metadata_url is string
  tags: idpmeta

- name: Fetch IdP metadata from one source
  get_url:
    url: "{{ mellon_sp_remote_idp_metadata_url[0] }}"
    dest: "{{ mellon_sp_cfg_dir }}/idp.xml"
    force: yes
  when: mellon_sp_remote_idp_metadata_url | length == 1
  tags: idpmeta

- name: Fetch IdP metadata from multiple sources
  get_url:
    url: "{{ item }}"
    dest: "{{ mellon_sp_cfg_dir }}/idp_{{ idx }}.xml"
    force: yes
  loop: "{{ mellon_sp_remote_idp_metadata_url }}"
  loop_control:
    index_var: idx
  when: mellon_sp_remote_idp_metadata_url | length > 1
  tags: idpmeta
