---
# Tasks
# TODO make this dependent on the apache role instead of installing the package
- name: Ensure apache2 mellon module is installed
  package:
    name: libapache2-mod-auth-mellon
    state: present


- name: Ensure mellon config directory exists
  file:
    path: "{{ mellon_sp_cfg_dir }}"
    state: directory
    mode: 0755


- name: Ensure SAML key is available
  copy:
    content: "{{ mellon_sp_key }}"
    dest: "{{ mellon_sp_cfg_dir }}/sp.key"
    mode: 0640
    group: "ssl-cert"


- name: Ensure SAML cert is available
  copy:
    content: "{{ mellon_sp_crt }}"
    dest: "{{ mellon_sp_cfg_dir }}/sp.crt"


- name: Fetch IdP metadata from "{{ mellon_sp_remote_idp_metadata_url }}"
  get_url:
    url: "{{ mellon_sp_remote_idp_metadata_url }}"
    dest: "{{ mellon_sp_cfg_dir }}/idp.xml"
    force: yes
  tags: idpmeta
